server:
  port: 18080 #端口号
  servlet:
    context-path: /exam-online #项目访问地址

spring:
  datasource:
    username: root
    password: "062013"
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url:  jdbc:p6spy:mysql://localhost:3306/examonline

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #日志输出
  type-aliases-package: com.wzy.exam_online.bean
  mapper-locations: classpath*:mapper/**/*.xml #别名包路径
  global-config:
    db-config:
      id-type: auto  #主键自增

